server:
  port: 8080

spring:
  datasource:
#    stringtype=unspecified to fix casting varchars to enums in Postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/appdb?stringtype=unspecified
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  data:
    web:
      pageable:
        max-page-size: 50

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.oldjopa.hls: DEBUG
