# application.yml
server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}?stringtype=unspecified"
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASS:apppass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  data:
    web:
      pageable:
        max-page-size: ${MAX_PAGE_SIZE:50}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.oldjopa.hls: DEBUG